# <center>NUMPY</center>

* Computação Científica: facilita as operações matemáticas avançadas e outros tipos de operações em muitos dados.

* Trabalha com Objetos de Matriz Multidimensional.

* Variedade de Rotinas para Operações Rápidas em Matrizes

* Os arrays NumPy têm um tamanho fixo na criação, ao contrário das listas Python (que podem crescer dinamicamente).

* Os elementos em uma matriz numpy devem ser todos do mesmo tipo de dados e, portanto, terão o mesmo tamanho.

In [162]:
import numpy as np

## Criação de Matrizes

### Matrizes Unidimensionais

* Matrizes unidimensionais podem ser confundidas com vetores de caracteres e podem ser criadas passando-se como parâmetro uma lista de valores para o método `np.array(<lista>)`.

In [163]:
mt = np.array([12,34,26,18,10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


### Tipos de Dados nas Matrizes

* Os arrays em Numpy precisam ser compostos de apenas um único tipo de dado, de modo que podemos, inclusive, especificar qual seja por meio do parâmetro `dtype=`.

In [164]:
# Array de Float 64 bits
mtfloat = np.array([1,2,3], dtype=np.float64)
print(mtfloat, type(mtfloat))

# Array de inteiros
mtint = np.array([1,2,3], dtype=np.int32)
print(mtint, type(mtint))

[1. 2. 3.] <class 'numpy.ndarray'>
[1 2 3] <class 'numpy.ndarray'>


* É possível alterar os valores de `dtype` de acordo com as necessidades.

In [165]:
# Criação de um array de float
mtnew = np.array([1.4,3.6,-5.1,9.42,4.9999999], dtype=np.float64)
print (mtnew, type(mtnew))

# Mudar o tipo de array para inteiro
mtnewint = mtnew.astype(np.int32)
print(mtnewint, type(mtnewint))

[ 1.4        3.6       -5.1        9.42       4.9999999] <class 'numpy.ndarray'>
[ 1  3 -5  9  4] <class 'numpy.ndarray'>


### Matrizes Multidimensionais

* É possível criar matrizes multidimensionais. Basta aninhar listas dentro de listas, criando dimensões internas. As tabelas, por exemplo, são matrizes bidimensionais (compostas por linhas e colunas).

In [166]:
# Criação de uma matriz bidimensional
tabela = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(tabela)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Matriz Sem Valores Declarados

* O método `np.empty([<linhas>, <colunas>], <tipo>)` cria uma matriz, porém não inicializa seus valores. Seu print mostra lixo de memória.

In [167]:
empty = np.empty([3,2], dtype=int)
print(empty)

[[                  0 4599094494223104511]
 [4602266672337769981 4603598093850475007]
 [4604470981647418113 4605184182907807742]]


### Matrizes Constantes

* O método  `np.zeros([<linhas>,<colunas>])` cria uma matriz nula.

In [168]:
zeros = np.zeros([4,3])
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


* O método `np.ones([<linhas>, <colunas>])` cria uma matriz numérica composta apenas por números 1.

In [169]:
ones = np.ones([5,7])
ones

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

### Matriz Identidade

* É possível também criar uma matriz identidade (matriz quadrada com diagonal valendo 1 e demais valores 0), utilizando o comando `np.eye(<linhas/colunas>)`.

In [170]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Extração de Elementos

A extração de elementos de uma matriz pode apresentar alguns resultados que não exatamente intuitivos. Por isso, precisamos prestar atenção nessas variações.

* **Observação 1**: a contagem do range e dos valores de extração incluem os valores indicados no index do começo e excluem os valores indicados pelo index do final. Assim, o intervalo de index 0-3 vai conter os valores dos índices indicados em 0,1,2.

* **Observação 2**: a ausência de valores não implica em nulidade, mas tão somente que a referência é o começo ou o final do array.

* **Observação 3**: valores negativos podem ser usados para indexar de modo reverso o array, sendo o -1 o último, o -2 o antepenúltimo, etc. Cabe ressaltar que o zero será sempre o primeira na ordem direta.

* **Observação 4**: a indexação de valores começa a contagem a partir do elemento 0 (zero).

### Array Unidimensional

In [171]:
unidimensional = np.array(range(11))

print('Posicao Única(3):',unidimensional[3])
print('Intervalo (index 1 a 5):',unidimensional[1:5])
print('Index até Final (index 3 até final):',unidimensional[3:])
print('Início até Index (Até 5)',unidimensional[:5])
print('Último (-1)',unidimensional[-1])
print('Penúltimo (-2)',unidimensional[-2])

Posicao Única(3): 3
Intervalo (index 1 a 5): [1 2 3 4]
Index até Final (index 3 até final): [ 3  4  5  6  7  8  9 10]
Início até Index (Até 5) [0 1 2 3 4]
Último (-1) 10
Penúltimo (-2) 9


### Array Multidimensional

In [172]:
print(tabela)
print('Linha/Colunas', tabela[0,:], tabela[:,0])
print('Célula Específica', tabela[1,2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Linha/Colunas [1 2 3] [1 4 7]
Célula Específica 6


## Operações com Matrizes

### Matrizes de Referência

In [173]:
a = np.arange(12)
b = 2*np.arange(12)
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  2  4  6  8 10 12 14 16 18 20 22]


### Operações Matemáticas

In [174]:
soma = a+b
mult_escalar = 10*a
print(soma)
print(mult_escalar)

[ 0  3  6  9 12 15 18 21 24 27 30 33]
[  0  10  20  30  40  50  60  70  80  90 100 110]


### Operações de Rearranjo

In [175]:
print('Array Original:\n',op1)
print('Matriz(2x6):\n', op1.reshape([2,6]))
print('Matriz(3x4):\n',op1.reshape([3,4]))

Array Original:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Matriz(2x6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Matriz(3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Operações de Tranposição

In [193]:
print('Matriz Original:\n',op1.reshape([3,4]))
print('Matriz Transposta:\n',op1.reshape([3,4]).T)
print('Matriz Transposta (transpose):\n',op1.reshape([3,4]).transpose())

Matriz Original:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Matriz Transposta:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Matriz Transposta (transpose):
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### Operações Lógicas

Existem métodos interessantes que permitem manipular os valores dos dados de acordo com uma determinada lógica. Por exemplo, é possível criar uma matriz de valores booleanos de acordo com um determinado critério. Ou atribuir valores personalizados quando cumprir uma determinada condições lógica. O método é bastante promissor.

In [194]:
logicos = np.random.randn(4,4)
logicos

array([[ 0.19380804, -0.56777037, -0.91021039, -1.1617464 ],
       [ 0.91505869,  2.05046801, -0.93598821,  0.55840725],
       [-1.13853044,  0.47706304, -1.33559678, -0.06416776],
       [ 0.62878944,  0.00877591,  1.10519256,  1.30721453]])

In [196]:
booleanos = (logicos > 0)
booleanos

array([[ True, False, False, False],
       [ True,  True, False,  True],
       [False,  True, False, False],
       [ True,  True,  True,  True]])

In [198]:
personalizado = np.where(logicos>0, 'POSITIVO', 'NEGATIVO')
personalizado

array([['POSITIVO', 'NEGATIVO', 'NEGATIVO', 'NEGATIVO'],
       ['POSITIVO', 'POSITIVO', 'NEGATIVO', 'POSITIVO'],
       ['NEGATIVO', 'POSITIVO', 'NEGATIVO', 'NEGATIVO'],
       ['POSITIVO', 'POSITIVO', 'POSITIVO', 'POSITIVO']], dtype='<U8')

## Métodos de Apoio Matemático

### Números Randômicos

* É possível gerar números randômicos entre 0 e 1 com métodos nativos de Python, utilizando o método `np.random.random(<quantidadeNumerosGerados>)`. O parâmetro do método indica quantos números deveram ser gerados randomicamente. A manipulação dos dados de retorno garante o uso de limites inferiores ou superiores diferentes de 0 e 1.

In [176]:
cinco_aletaroios = np.random.random(5)
cinco_aletaroios

array([0.65497655, 0.98296991, 0.66298184, 0.85174275, 0.80506259])

* É possível criar uma matriz com a função random, utilizando como parâmetro as dimensões de uma matriz. A sintaxe pode ser feita da seguinte forma: `np.random.random((<linhas>,<colunas>))`

In [177]:
matriz_random = np.ceil(10*np.random.random((3,4)))
matriz_random

array([[4., 6., 8., 8.],
       [1., 8., 2., 5.],
       [9., 4., 9., 8.]])

* É possível gerar números inteiros diretamente dentro de um limite informado, utilizando o método `np.random.randint(low=<menor>,high=<maior>)`

In [178]:
random_int = np.random.randint(low=5,high=30)
random_int

21

### Distribuição Randômica Gaussiana

* É possível obter números randômicos distribuídos de forma a gerar conjuntos de dados que obedecem à distribuição normal entre -1 e 1. Para tanto, utiliza-se o método `np.random.randn(<quantidadeNumerosGerados>)`

In [179]:
distribuicao_normal = np.random.randn(5)
distribuicao_normal

array([-1.58238851,  0.87862919, -0.06740949,  0.54129316, -0.57314642])

### Números com Sementes

* É possível usar sementes para geração de números com resultados determinísticos. A sintaxe exige que seja definida uma semente de referência por meio do método `np.random.default_rng(<semente>)`. O retorno dessa função será um objeto que têm métodos de geração de números randmicos ou numeros inteiros, etc.

In [180]:
numeros_semente = np.random.default_rng(10)
teste1 = numeros_semente.random(5)
print(teste1)

[0.95600171 0.20768181 0.82844489 0.14928212 0.51280462]


* É possível criar matrizes determinísticas com valores limitados inferior e superiormente utilizando métodos associados ao np.random.default_rng. Basta usar o método `<variavelSemente>.integers()`, sendo certo que devemos informar os limites e o formato da matriz.

In [181]:
teste2 = numeros_semente.integers(low=3, high=30, size=(3,4))
print(teste2)

[[ 7  6 14 21]
 [13 25  3 14]
 [17 28  9 25]]


### Conjuntos de Valores Únicos

* É possível transformar uma lista ou array de dados em um conjunto de dados únicos utilizando o método `np.unique()`.

In [182]:
repetidos = np.array([1,2,3,3,2,3,2,3,2,4,42,4,4,4,4,4,4,4,4,10,23])
print(repetidos)

unicos = np.unique(repetidos)
print(unicos)

[ 1  2  3  3  2  3  2  3  2  4 42  4  4  4  4  4  4  4  4 10 23]
[ 1  2  3  4 10 23 42]


### Funções Específicas

* É possível avaliar quais as dimensões de uma matriz utilizando o método `<array>.shape`.

In [183]:
tabela.shape

(3, 3)

* É possível utilizar métodos de estatística descritiva de forma simplificada.

In [184]:
average = np.average(repetidos)
desvio_padrao = np.std(repetidos)
variancia = np.var(repetidos)
covariancia = np.cov(repetidos)
print('Media',average)
print('Desvio Padrao',desvio_padrao)
print('Variancia',variancia)
print('Covariancia',covariancia)

Media 6.285714285714286
Desvio Padrao 9.155497214881379
Variancia 83.82312925170068
Covariancia 88.01428571428572


* É possível utilizar métodos do array Numpy para sobre os dados do array.

In [185]:
print('Maximo',repetidos.max())
print('Minimo',repetidos.min())
print('Soma',repetidos.sum())
print('Media',repetidos.mean())
print('Desvio Padrão',repetidos.std())

Maximo 42
Minimo 1
Soma 132
Media 6.285714285714286
Desvio Padrão 9.155497214881379


### Funções Matemáticas Universais

In [186]:
funcoes = np.array([1,2,3,4,5,6])
exponencial = np.exp(funcoes)
raizquadrada = np.sqrt(funcoes)
logn = np.log(funcoes)
log10 = np.log10(funcoes)
print(funcoes)
print(exponencial)
print(raizquadrada)
print(logn)
print(log10)

[1 2 3 4 5 6]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125]


##